apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xnc-orderer0
  namespace: xnc-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: xnc-orderer0
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: xnc-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer0
      loglevel: info
      localmspid: xncMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: xncsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://101.36.106.59:8200
      role: vault-role
      authpath: devxnc-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/xnc-net/orderers/orderer0.xnc-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.xnc-net.svc.cluster.local:9092
      - kafka-1.broker.xnc-net.svc.cluster.local:9092
      - kafka-2.broker.xnc-net.svc.cluster.local:9092
      - kafka-3.broker.xnc-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: xncambassador.blockchain.liubaninc.cn

    genesis: |-
      CiIaIGez8zWUk3grwgxrnZRy3mJFYC4c7rDDF/j/6Awnb4onEpNNCpBNCo1NCngKWggBEAEaBgiC
      hY2QBiIKc3lzY2hhbm5lbCpAZDM1YTk3YTNkNWRiYjg1MmYwMzJhMzBhMGJiYjVmMTVjOTBhYjRj
      OTliMDZiZWUxZjE3ZmIyNzBkYmQwNWE3YxIaEhia25QJCYBd69eqJbYUBmvFygRVAtzklR0SkEwK
      jUwSikwSiRwKB09yZGVyZXIS/RsS0BcKBnhuY01TUBLFFxrxFQoDTVNQEukVEt4VEtsVCgZ4bmNN
      U1ASwgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ096Q0NBZUtnQXdJQkFnSVVPb3pO
      TlpUTXhZc1VicGY2ZHZyZTVESW1PUjh3Q2dZSUtvWkl6ajBFQXdJdwpmREVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1Ua3dOd1lEVlFRREREQmpZUzU0Ym1NdGJtVjBMbmh1WTJGdFltRnoK
      YzJGa2IzSXVZbXh2WTJ0amFHRnBiaTVzYVhWaVlXNXBibU11WTI0d0hoY05Nakl3TWpBNU1ESTBN
      elUxV2hjTgpNalF4TVRJNU1ESTBNelUxV2pCOE1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVD
      QXdHVEc5dVpHOXVNUTh3CkRRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnla
      WEl4T1RBM0JnTlZCQU1NTUdOaExuaHUKWXkxdVpYUXVlRzVqWVcxaVlYTnpZV1J2Y2k1aWJHOWph
      Mk5vWVdsdUxteHBkV0poYm1sdVl5NWpiakJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhB
      MElBQk9YZUNIT0tVN3FnbUFoYlIzS3NOdEJEMmxiLzdpTVU0S1B5Cit3WUZkWjZqMDE3ZDFWelZu
      MHVYNTR1VUk3dnZKODRRWExIMUFINm9vTk5NRFNhUGphdWpRakJBTUE4R0ExVWQKRXdFQi93UUZN
      QU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUTnNQc1JzVXk1VFNnRAox
      Q0FJenl4b0U0VDhvVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUI4UmFKWVpCViswcVNRdFp0eDU3
      WjhtYlkwClB4NU5nS2ZYU2Z6MDRYK3hPQUlnUnI1SGFTbnUvK1FUREVESWNPbFhPRUtpeFhaMzhj
      RUVSL1hpM1k5NWpmUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFdnQXdJQkFnSVVWeUYzZjlXd2ZCUE9sdjlkNFoxRmly
      cWxpUk13Q2dZSUtvWkl6ajBFQXdJdwpmREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1U
      a3dOd1lEVlFRREREQmpZUzU0Ym1NdGJtVjBMbmh1WTJGdFltRnoKYzJGa2IzSXVZbXh2WTJ0amFH
      RnBiaTVzYVhWaVlXNXBibU11WTI0d0hoY05Nakl3TWpBNU1ESTBPVEF3V2hjTgpNak13TWpBNU1E
      STFOREF3V2pCa01Rc3dDUVlEVlFRR0V3SkhRakViTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1Ck1U
      TXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHdEQVlEVlFRTEV3VmhaRzFwYmpF
      V01CUUcKQTFVRUF3d05RV1J0YVc1QWVHNWpMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQkhpRQpwWE8wY29hOUhqVXRHa0x6MmU4QmtYWHN4UlVXM2lpMng4bGY5aHZub1Zp
      aitWRzY1T1NXQ3NwUjVkcHVab1dxCmpFaUZIbTQ5TmcvNjRRWUhGdldqZ2dFTE1JSUJCekFPQmdO
      VkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC8KQkFJd0FEQWRCZ05WSFE0RUZnUVV0WnphYzRv
      dnJKbkYwTXNEVGptbWVpRGZTbUF3SHdZRFZSMGpCQmd3Rm9BVQp6YkQ3RWJGTXVVMG9BOVFnQ004
      c2FCT0UvS0V3SXdZRFZSMFJCQnd3R29JWVkyRXRkRzl2YkhNdE9XWTJaRGhtClpEUTVMVGQwWm5K
      NE1JR0JCZ2dxQXdRRkJnY0lBUVIxZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaU9pSjAKY25W
      bElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lJaUxDSm9aaTVG
      Ym5KdgpiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQjRibU10Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbUZr
      YldsdUluMTlNQW9HCkNDcUdTTTQ5QkFNQ0EwY0FNRVFDSUd4OTFZRWl3Y2lkbTk1YWxjQlRMYlJl
      ZXJhVmI0SE4rR09zTUdjdXpGY0YKQWlCMGFGRnhmdFBUSC9IOUtNdEM0MG5kMkd3ZjNuYklERkVR
      QWFQQ1Rmc1ErUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrC
      Bi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDT3pDQ0FlS2dBd0lCQWdJVU9vek5OWlRN
      eFlzVWJwZjZkdnJlNURJbU9SOHdDZ1lJS29aSXpqMEVBd0l3CmZERUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkUGNtUmxjbVZ5TVRrd053WURWUVFERERCallTNTRibU10Ym1WMExuaHVZMkZ0WW1GegpjMkZr
      YjNJdVlteHZZMnRqYUdGcGJpNXNhWFZpWVc1cGJtTXVZMjR3SGhjTk1qSXdNakE1TURJME16VTFX
      aGNOCk1qUXhNVEk1TURJME16VTFXakI4TVFzd0NRWURWUVFHRXdKSFFqRVBNQTBHQTFVRUNBd0dU
      Rzl1Wkc5dU1ROHcKRFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeVpYSXhP
      VEEzQmdOVkJBTU1NR05oTG5odQpZeTF1WlhRdWVHNWpZVzFpWVhOellXUnZjaTVpYkc5amEyTm9Z
      V2x1TG14cGRXSmhibWx1WXk1amJqQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFC
      T1hlQ0hPS1U3cWdtQWhiUjNLc050QkQybGIvN2lNVTRLUHkKK3dZRmRaNmowMTdkMVZ6Vm4wdVg1
      NHVVSTd2dko4NFFYTEgxQUg2b29OTk1EU2FQamF1alFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJB
      Zjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlROc1BzUnNVeTVUU2dECjFDQUl6
      eXhvRTRUOG9UQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQjhSYUpZWkJWKzBxU1F0WnR4NTdaOG1i
      WTAKUHg1TmdLZlhTZnowNFgreE9BSWdScjVIYVNudS8rUVRERURJY09sWE9FS2l4WFozOGNFRVIv
      WGkzWTk1amZRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjAKBkFkbWlucxIm
      EhwIARIYEggSBggBEgIIABoMEgoKBnhuY01TUBABGgZBZG1pbnMiMwoLRW5kb3JzZW1lbnQSJBIa
      CAESFhIIEgYIARICCAAaChIICgZ4bmNNU1AaBkFkbWlucyIvCgdSZWFkZXJzEiQSGggBEhYSCBIG
      CAESAggAGgoSCAoGeG5jTVNQGgZBZG1pbnMiLwoHV3JpdGVycxIkEhoIARIWEggSBggBEgIIABoK
      EggKBnhuY01TUBoGQWRtaW5zKgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAa
      BkFkbWlucxrYAQoMS2Fma2FCcm9rZXJzEscBErwBCi1rYWZrYS0wLmJyb2tlci54bmMtbmV0LnN2
      Yy5jbHVzdGVyLmxvY2FsOjkwOTIKLWthZmthLTEuYnJva2VyLnhuYy1uZXQuc3ZjLmNsdXN0ZXIu
      bG9jYWw6OTA5Mgota2Fma2EtMi5icm9rZXIueG5jLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDky
      Ci1rYWZrYS0zLmJyb2tlci54bmMtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIaBkFkbWlucxoi
      Cg1Db25zZW5zdXNUeXBlEhESBwoFa2Fma2EaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICA
      MRiAgEAaBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxS
      ZXN0cmljdGlvbnMSCBoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5z
      IioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIX
      Eg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMqBkFkbWlucxLtLAoLQ29uc29ydGl1bXMS3SwSkiwKDXhuY0NvbnNvcnRpdW0SgCwSoisKBnhu
      ZE1TUBKXKxrDKQoDTVNQErspErApEq0pCgZ4bmRNU1ASugYtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQ05UQ0NBZHFnQXdJQkFnSVVGU0JjVHd1Tm5oeDVXTVBSNzZObmdOdHhpUlF3Q2dZ
      SUtvWkl6ajBFQXdJdwplREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1Rd3dDZ1lEVlFRS0RBTjRibVF4T1RBM0JnTlZCQU1NTUdO
      aExuaHVaQzF1WlhRdWVHNWtZVzFpWVhOellXUnYKY2k1aWJHOWphMk5vWVdsdUxteHBkV0poYm1s
      dVl5NWpiakFlRncweU1qQXlNRGt3TWpRMU5UWmFGdzB5TkRFeApNamt3TWpRMU5UWmFNSGd4Q3pB
      SkJnTlZCQVlUQWtOSU1ROHdEUVlEVlFRSURBWmFkWEpwWTJneER6QU5CZ05WCkJBY01CbHAxY21s
      amFERU1NQW9HQTFVRUNnd0RlRzVrTVRrd053WURWUVFERERCallTNTRibVF0Ym1WMExuaHUKWkdG
      dFltRnpjMkZrYjNJdVlteHZZMnRqYUdGcGJpNXNhWFZpWVc1cGJtTXVZMjR3V1RBVEJnY3Foa2pP
      UFFJQgpCZ2dxaGtqT1BRTUJCd05DQUFRYXJxUkFUMU42N0E3S0p2RENnT05uNSttQ0pHbkQ3cEFi
      SW9NdGFiTHJHNlQ3ClRJSkg0RnRjcjhmZzlEMkw2TWMrSUM3elBuRzg3dzZkL1VaVXF5dGJvMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVURJemYvQWh6b3U2UXo0NWJxTGI5bWNXQwpiaHd3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0lo
      QU5GOG5HYmZ5M0FXVW5GRUppRUV2TmFmWTVjc2hFcmwya2pjCktuajZpTVpBQWlFQTdkWktVa1E5
      YW5xcGFvZ1c0K1M5RWZlc0JFS3doRUIvWklZbE9VL2p0Y1k9Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KIr4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5akNDQXB5Z0F3SUJBZ0lV
      VWt0TG01R0o1dVVvd2dDSlpUZGZnaFhqNXFJd0NnWUlLb1pJemowRUF3SXcKZURFTE1Ba0dBMVVF
      QmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUXd3
      Q2dZRFZRUUtEQU40Ym1ReE9UQTNCZ05WQkFNTU1HTmhMbmh1WkMxdVpYUXVlRzVrWVcxaVlYTnpZ
      V1J2CmNpNWliRzlqYTJOb1lXbHVMbXhwZFdKaGJtbHVZeTVqYmpBZUZ3MHlNakF5TURrd01qVXhN
      REJhRncweU16QXkKTURrd01qVTJNREJhTUdzeEN6QUpCZ05WQkFZVEFrTklNUm93R0FZRFZRUUhF
      eEUwTnk0ek9DODRMalUwTDFwMQpjbWxqYURFTU1Bb0dBMVVFQ2hNRGVHNWtNUm93REFZRFZRUUxF
      d1ZoWkcxcGJqQUtCZ05WQkFzVEEzaHVaREVXCk1CUUdBMVVFQXd3TlFXUnRhVzVBZUc1a0xXNWxk
      REJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUEKQklNWndKbEVpWDF6aWlYL2Z1OSs0
      NklXRTB1R0o3bUhuL0JKQUpFT0pEUzFBQTFwRWxtaWtweG9Cc1YvaWIrRwovVUIvMFZtTElPbkVp
      MVpzU0VSdVBzeWpnZ0VQTUlJQkN6QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUCkFRSC9C
      QUl3QURBZEJnTlZIUTRFRmdRVXErVXBscUhEWjh6aWxFazNucTVkSDZKNmNkd3dId1lEVlIwakJC
      Z3cKRm9BVURJemYvQWh6b3U2UXo0NWJxTGI5bWNXQ2Jod3dKQVlEVlIwUkJCMHdHNElaWTJFdGRH
      OXZiSE10Tm1JMQpPRFZtT0dNNU5pMXJkSGQ2ZERDQmhBWUlLZ01FQlFZSENBRUVlSHNpWVhSMGNu
      TWlPbnNpWVdKaFl5NXBibWwwCklqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxr
      Rm1abWxzYVdGMGFXOXVJam9pZUc1a0lpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFX
      NUFlRzVrTFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcApiaUo5ZlRBS0JnZ3Foa2pPUFFRREFn
      TklBREJGQWlFQTEwd1NVOFF2Qm5aTkkrQnVSQzlNM05IcU0zRThSUEdYCmFXZFo0QlAzSDdVQ0lB
      U29QNHJtODJCQTQvTlRyeWRRd3RVYlRURk9yNGs2dlB4OHViV1N6eFQ1Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkq6Bi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDTlRDQ0FkcWdBd0lCQWdJVUZTQmNUd3VObmh4NVdNUFI3Nk5uZ050eGlSUXdDZ1lJS29a
      SXpqMEVBd0l3CmVERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVF3d0NnWURWUVFLREFONGJtUXhPVEEzQmdOVkJBTU1NR05oTG5o
      dVpDMXVaWFF1ZUc1a1lXMWlZWE56WVdSdgpjaTVpYkc5amEyTm9ZV2x1TG14cGRXSmhibWx1WXk1
      amJqQWVGdzB5TWpBeU1Ea3dNalExTlRaYUZ3MHlOREV4Ck1qa3dNalExTlRaYU1IZ3hDekFKQmdO
      VkJBWVRBa05JTVE4d0RRWURWUVFJREFaYWRYSnBZMmd4RHpBTkJnTlYKQkFjTUJscDFjbWxqYURF
      TU1Bb0dBMVVFQ2d3RGVHNWtNVGt3TndZRFZRUUREREJqWVM1NGJtUXRibVYwTG5odQpaR0Z0WW1G
      emMyRmtiM0l1WW14dlkydGphR0ZwYmk1c2FYVmlZVzVwYm1NdVkyNHdXVEFUQmdjcWhrak9QUUlC
      CkJnZ3Foa2pPUFFNQkJ3TkNBQVFhcnFSQVQxTjY3QTdLSnZEQ2dPTm41K21DSkduRDdwQWJJb010
      YWJMckc2VDcKVElKSDRGdGNyOGZnOUQyTDZNYytJQzd6UG5HODd3NmQvVVpVcXl0Ym8wSXdRREFQ
      QmdOVkhSTUJBZjhFQlRBRApBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      REl6Zi9BaHpvdTZRejQ1YnFMYjltY1dDCmJod3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTkY4
      bkdiZnkzQVdVbkZFSmlFRXZOYWZZNWNzaEVybDJramMKS25qNmlNWkFBaUVBN2RaS1VrUTlhbnFw
      YW9nVzQrUzlFZmVzQkVLd2hFQi9aSVlsT1UvanRjWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQpa1xMIARLFBgq6Bi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDTlRDQ0FkcWdBd0lC
      QWdJVUZTQmNUd3VObmh4NVdNUFI3Nk5uZ050eGlSUXdDZ1lJS29aSXpqMEVBd0l3CmVERUxNQWtH
      QTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8K
      TVF3d0NnWURWUVFLREFONGJtUXhPVEEzQmdOVkJBTU1NR05oTG5odVpDMXVaWFF1ZUc1a1lXMWlZ
      WE56WVdSdgpjaTVpYkc5amEyTm9ZV2x1TG14cGRXSmhibWx1WXk1amJqQWVGdzB5TWpBeU1Ea3dN
      alExTlRaYUZ3MHlOREV4Ck1qa3dNalExTlRaYU1IZ3hDekFKQmdOVkJBWVRBa05JTVE4d0RRWURW
      UVFJREFaYWRYSnBZMmd4RHpBTkJnTlYKQkFjTUJscDFjbWxqYURFTU1Bb0dBMVVFQ2d3RGVHNWtN
      VGt3TndZRFZRUUREREJqWVM1NGJtUXRibVYwTG5odQpaR0Z0WW1GemMyRmtiM0l1WW14dlkydGph
      R0ZwYmk1c2FYVmlZVzVwYm1NdVkyNHdXVEFUQmdjcWhrak9QUUlCCkJnZ3Foa2pPUFFNQkJ3TkNB
      QVFhcnFSQVQxTjY3QTdLSnZEQ2dPTm41K21DSkduRDdwQWJJb010YWJMckc2VDcKVElKSDRGdGNy
      OGZnOUQyTDZNYytJQzd6UG5HODd3NmQvVVpVcXl0Ym8wSXdRREFQQmdOVkhSTUJBZjhFQlRBRApB
      UUgvTUE0R0ExVWREd0VCL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVREl6Zi9BaHpvdTZRejQ1YnFM
      YjltY1dDCmJod3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTkY4bkdiZnkzQVdVbkZFSmlFRXZO
      YWZZNWNzaEVybDJramMKS25qNmlNWkFBaUVBN2RaS1VrUTlhbnFwYW9nVzQrUzlFZmVzQkVLd2hF
      Qi9aSVlsT1UvanRjWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBmNsaWVudBrDBgq6Bi0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDTlRDQ0FkcWdBd0lCQWdJVUZTQmNUd3VObmh4
      NVdNUFI3Nk5uZ050eGlSUXdDZ1lJS29aSXpqMEVBd0l3CmVERUxNQWtHQTFVRUJoTUNRMGd4RHpB
      TkJnTlZCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVF3d0NnWURWUVFLREFO
      NGJtUXhPVEEzQmdOVkJBTU1NR05oTG5odVpDMXVaWFF1ZUc1a1lXMWlZWE56WVdSdgpjaTVpYkc5
      amEyTm9ZV2x1TG14cGRXSmhibWx1WXk1amJqQWVGdzB5TWpBeU1Ea3dNalExTlRaYUZ3MHlOREV4
      Ck1qa3dNalExTlRaYU1IZ3hDekFKQmdOVkJBWVRBa05JTVE4d0RRWURWUVFJREFaYWRYSnBZMmd4
      RHpBTkJnTlYKQkFjTUJscDFjbWxqYURFTU1Bb0dBMVVFQ2d3RGVHNWtNVGt3TndZRFZRUUREREJq
      WVM1NGJtUXRibVYwTG5odQpaR0Z0WW1GemMyRmtiM0l1WW14dlkydGphR0ZwYmk1c2FYVmlZVzVw
      Ym1NdVkyNHdXVEFUQmdjcWhrak9QUUlCCkJnZ3Foa2pPUFFNQkJ3TkNBQVFhcnFSQVQxTjY3QTdL
      SnZEQ2dPTm41K21DSkduRDdwQWJJb010YWJMckc2VDcKVElKSDRGdGNyOGZnOUQyTDZNYytJQzd6
      UG5HODd3NmQvVVpVcXl0Ym8wSXdRREFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUE0R0ExVWREd0VC
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVREl6Zi9BaHpvdTZRejQ1YnFMYjltY1dDCmJod3dDZ1lJ
      S29aSXpqMEVBd0lEU1FBd1JnSWhBTkY4bkdiZnkzQVdVbkZFSmlFRXZOYWZZNWNzaEVybDJramMK
      S25qNmlNWkFBaUVBN2RaS1VrUTlhbnFwYW9nVzQrUzlFZmVzQkVLd2hFQi9aSVlsT1UvanRjWT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBHBlZXIixAYKugYtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ05UQ0NBZHFnQXdJQkFnSVVGU0JjVHd1Tm5oeDVXTVBSNzZObmdOdHhpUlF3
      Q2dZSUtvWkl6ajBFQXdJdwplREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxq
      YURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1Rd3dDZ1lEVlFRS0RBTjRibVF4T1RBM0JnTlZCQU1N
      TUdOaExuaHVaQzF1WlhRdWVHNWtZVzFpWVhOellXUnYKY2k1aWJHOWphMk5vWVdsdUxteHBkV0po
      Ym1sdVl5NWpiakFlRncweU1qQXlNRGt3TWpRMU5UWmFGdzB5TkRFeApNamt3TWpRMU5UWmFNSGd4
      Q3pBSkJnTlZCQVlUQWtOSU1ROHdEUVlEVlFRSURBWmFkWEpwWTJneER6QU5CZ05WCkJBY01CbHAx
      Y21samFERU1NQW9HQTFVRUNnd0RlRzVrTVRrd053WURWUVFERERCallTNTRibVF0Ym1WMExuaHUK
      WkdGdFltRnpjMkZrYjNJdVlteHZZMnRqYUdGcGJpNXNhWFZpWVc1cGJtTXVZMjR3V1RBVEJnY3Fo
      a2pPUFFJQgpCZ2dxaGtqT1BRTUJCd05DQUFRYXJxUkFUMU42N0E3S0p2RENnT05uNSttQ0pHbkQ3
      cEFiSW9NdGFiTHJHNlQ3ClRJSkg0RnRjcjhmZzlEMkw2TWMrSUM3elBuRzg3dzZkL1VaVXF5dGJv
      MEl3UURBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCcGpBZEJnTlZI
      UTRFRmdRVURJemYvQWh6b3U2UXo0NWJxTGI5bWNXQwpiaHd3Q2dZSUtvWkl6ajBFQXdJRFNRQXdS
      Z0loQU5GOG5HYmZ5M0FXVW5GRUppRUV2TmFmWTVjc2hFcmwya2pjCktuajZpTVpBQWlFQTdkWktV
      a1E5YW5xcGFvZ1c0K1M5RWZlc0JFS3doRUIvWklZbE9VL2p0Y1k9Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KEgVhZG1pbhoGQWRtaW5zIjAKBkFkbWlucxImEhwIARIYEggSBggBEgIIABoMEgoK
      BnhuZE1TUBABGgZBZG1pbnMiMwoLRW5kb3JzZW1lbnQSJBIaCAESFhIIEgYIARICCAAaChIICgZ4
      bmRNU1AaBkFkbWlucyIvCgdSZWFkZXJzEiQSGggBEhYSCBIGCAESAggAGgoSCAoGeG5kTVNQGgZB
      ZG1pbnMiLwoHV3JpdGVycxIkEhoIARIWEggSBggBEgIIABoKEggKBnhuZE1TUBoGQWRtaW5zKgZB
      ZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwv
      T3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIE
      EgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYK
      EEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5n
      U3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGpoBChBPcmRlcmVyQWRkcmVzc2VzEoUBEmoKM29y
      ZGVyZXIwLnhuY2FtYmFzc2Fkb3IuYmxvY2tjaGFpbi5saXViYW5pbmMuY246ODQ0Mwozb3JkZXJl
      cjEueG5jYW1iYXNzYWRvci5ibG9ja2NoYWluLmxpdWJhbmluYy5jbjo4NDQzGhcvQ2hhbm5lbC9P
      cmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKBkFk
      bWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVy
      cxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoE
      CgIKAAoACgAKAAoA
