##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.node.name }}
  namespace: {{ .Values.metadata.namespace }}
  {{- if eq .Values.proxy.provider "haproxy" }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
  {{- end }}
spec:
  rules:
  - host: {{ .Values.node.name }}rpc.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.node.name }}
            port:
              number: {{ .Values.node.ports.rpc }}
  - host: {{ .Values.node.name }}tcp.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.node.name }}
            port:
              number: {{ .Values.node.ports.quorum }}
  {{- if eq $.Values.node.consensus "raft" }}
  - host: {{ .Values.node.name }}raft.{{ .Values.proxy.external_url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ .Values.node.name }}
            port:
              number: {{ .Values.node.ports.raft }}
  {{- end }}