apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xnna-cacerts-job
  namespace: xnna-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: xnna-cacerts-job
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: xnna
      component_name: xnna-net
      namespace: xnna-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://101.36.106.59:8200
      authpath: devxnna-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/xnna-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/xnna-net/ca/xnna
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.xnna-net.xnnaambassador.blockchain.liubaninc.cn
