apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: xnb-cacerts-job
  namespace: xnb-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: xnb-cacerts-job
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: xnb
      component_name: xnb-net
      namespace: xnb-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://101.36.106.59:8200
      authpath: devxnb-net-auth
      secretcryptoprefix: secretsv2/data/crypto/peerOrganizations/xnb-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/xnb-net/ca/xnb
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=CH/ST=Zurich/L=Zurich/O=xnb/CN=ca.xnb-net.xnbambassador.blockchain.liubaninc.cn
