apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cccccc-v0quorum
  namespace: ccc-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cccccc-v0quorum
  helmVersion: v3
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local10
    path: platforms/quorum/charts/node_quorum_validator  
  values:
    replicaCount: 1
    metadata:
      namespace: ccc-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.4.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: ccc-v0
      status: default
      consensus: ibft
      subject: O=ccc-v0,OU=ccc-v0,L=42.36/-71.06/Boston,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
        cakeshop: 8080
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://101.36.106.59:8200
      secretprefix: secretsv2/data/ccc-quo/crypto/ccc-v0
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumccc
    tessera:
      dburl: "jdbc:mysql://ccc-v0-tessera:3306/demodb"
      dbusername: demouser
      url: "https://ccc-v0.test.blockchain.liubaninc.cn:443"
      clienturl: "http://ccc-v0-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://ccc-v0.test.blockchain.liubaninc.cn
        - url: https://ccc-v1.test.blockchain.liubaninc.cn
        - url: https://ccc-v2.test.blockchain.liubaninc.cn
        - url: https://ccc-m0.test.blockchain.liubaninc.cn
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjFkZDNlNWMiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDc3NjgzNWNkNzk3NDU3MjVmNTE4NTM5ODA0Njc4YTA2MGQ0ZGIzNWY5NGEzZDBjYTBmNTY5NDBkYjcwNzI0NzljNDE0ZmZmMDg4YzMyMGU1ZTU5NGIxOWFiNGM1Mzk1ZWFiNDk1NmRjYzJhYzA4MWJiNjAxY2I3NmVhYmY5NDIyZWJjMzhkNDNiY2E0YWNiYjFmMzIwYmQ2M2ViY2U1Y2M2MGIzN2ViODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICIyMmViYzM4ZDQzYmNhNGFjYmIxZjMyMGJkNjNlYmNlNWNjNjBiMzdlIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNzc2ODM1Y2Q3OTc0NTcyNWY1MTg1Mzk4MDQ2NzhhMDYwZDRkYjM1ZiI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImEzZDBjYTBmNTY5NDBkYjcwNzI0NzljNDE0ZmZmMDg4YzMyMGU1ZTUiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICJiMTlhYjRjNTM5NWVhYjQ5NTZkY2MyYWMwODFiYjYwMWNiNzZlYWJmIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://bebe678bb182007e09d076d70a724e630865fff188f119aee106c4e26d38aa6fdbc9f42bc3cb57b50ce6eabad32baf262d5f3f4fe5ab44c488b2e55d1aa78a1f@ccc-v0.test.blockchain.liubaninc.cn:15910?discport=0",
    "enode://241b5cc8efb2e57a8af17b21fa84a073b482782a7a13db23a63830b8c884a593ea1aa29b958db7b922a48cdbe67e80b25b8cf2a490b82ca3806724737e5646dd@ccc-v1.test.blockchain.liubaninc.cn:15920?discport=0",
    "enode://1929228648a6666b68a3bb8c0953cd4b01c282956a63d2176c365494c2825d70a0db7c9f8b6ea1bec8443e988e93fab8586abfff32cc41c6968a2f18c4bc9765@ccc-v2.test.blockchain.liubaninc.cn:15930?discport=0",
    "enode://209c5d9a6f8652d80eeaf0b32b7f5c1ef16eaa73a455a96981f6a5f2cc3baa085814e7a22922bcd0cdfbc5650a2910115008b4575e08502baeba3dec4a9e61db@ccc-m0.test.blockchain.liubaninc.cn:15900?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: ccc-v0.test.blockchain.liubaninc.cn
      portTM: 443
      rpcport: 15911
      quorumport: 15910
      cakeshopport: 15914
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
