apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cccccc-v2quorum
  namespace: ccc-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cccccc-v2quorum
  helmVersion: v3
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local10
    path: platforms/quorum/charts/node_quorum_validator  
  values:
    replicaCount: 1
    metadata:
      namespace: ccc-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.4.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: ccc-v2
      status: default
      consensus: ibft
      subject: O=ccc-v2,OU=ccc-v2,L=42.36/-71.06/Boston,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
        cakeshop: 8080
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://101.36.106.59:8200
      secretprefix: secretsv2/data/ccc-quo/crypto/ccc-v2
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumccc
    tessera:
      dburl: "jdbc:mysql://ccc-v2-tessera:3306/demodb"
      dbusername: demouser
      url: "https://ccc-v2.test.blockchain.liubaninc.cn:443"
      clienturl: "http://ccc-v2-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://ccc-v0.test.blockchain.liubaninc.cn
        - url: https://ccc-v1.test.blockchain.liubaninc.cn
        - url: https://ccc-v2.test.blockchain.liubaninc.cn
        - url: https://ccc-m0.test.blockchain.liubaninc.cn
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjFkZDM3ZTMiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDc2YjA2N2U2MjM0MGE5NzgxM2Y1NDI2NWNhZGU4YzNiZmVjNWY4N2Q5NGJjMzg4M2Y5ZTljZmQwYjY4MWIxZTgxMDY0YzE4YzU5NDQ5M2M0NDc5NDYzODU4MDM4OTUyMTM2ZTgxNjMxNmQ3ODA3N2Y1MmU0ZGM2MWQ0NGY5NDc5MDZhNWI2M2NjMTllNTVmYjExNDNmN2JjNmEyNWY2MWFjYWUyNzJiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICI2Mzg1ODAzODk1MjEzNmU4MTYzMTZkNzgwNzdmNTJlNGRjNjFkNDRmIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNzZiMDY3ZTYyMzQwYTk3ODEzZjU0MjY1Y2FkZThjM2JmZWM1Zjg3ZCI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjc5MDZhNWI2M2NjMTllNTVmYjExNDNmN2JjNmEyNWY2MWFjYWUyNzIiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICJiYzM4ODNmOWU5Y2ZkMGI2ODFiMWU4MTA2NGMxOGM1OTQ0OTNjNDQ3IjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://415d2b273e8e134439310820f05dc304ce2fad11e6c16479c1197b54ceb333697aaef7f152568d3c7367f085b9969afa07c2bff9c4d42b61e57c34bc71cd3901@ccc-v0.test.blockchain.liubaninc.cn:15910?discport=0",
    "enode://d57f83e46342bba22bdaac491a85ff2f19cd49bcb435c10353661064646094a4cd47e65fb66244d17d20199af43c73de94122542cce8e60ab209c7f3149b22de@ccc-v1.test.blockchain.liubaninc.cn:15920?discport=0",
    "enode://4748c9cf8a821b067e97e2228c0759e6a8ad9a65a0f0d30cfec694065e289d1e973f99792abaf028b1e90f263bfefe0ca5ec64129be0d87ea446414c4c71a08f@ccc-v2.test.blockchain.liubaninc.cn:15930?discport=0",
    "enode://d8fdf2326def0564800f58e36c01c91fabf8c6b189da16ddffd6000769541fd01c9b92a702d746af0b4996f8f1a16f5f6d7d4f4b0182d0b92aa869c409a9f51e@ccc-m0.test.blockchain.liubaninc.cn:15900?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: ccc-v2.test.blockchain.liubaninc.cn
      portTM: 443
      rpcport: 15931
      quorumport: 15930
      cakeshopport: 15934
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
