apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hha-orderer0
  namespace: hha-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: hha-orderer0
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: hha-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer0
      loglevel: info
      localmspid: hhaMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: hhasc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://101.36.106.59:8200
      role: vault-role
      authpath: devhha-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/hha-net/orderers/orderer0.hha-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.hha-net.svc.cluster.local:9092
      - kafka-1.broker.hha-net.svc.cluster.local:9092
      - kafka-2.broker.hha-net.svc.cluster.local:9092
      - kafka-3.broker.hha-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: hhaambassador.blockchain.liubaninc.cn

    genesis: |-
      CiIaIDkq8Y8DFq7u7nqLq/WJTQnNtquzFpU6CNpMUCvN7irGEuwhCukhCuYhCngKWggBEAEaBgio
      r8mPBiIKc3lzY2hhbm5lbCpAYTIzYTJhMTZhMTMxM2MzY2VhOGQ0OGRjNWZlOWRmYWE3Y2UzNDg4
      YjA1NGZmNDE0NmMwNGVmMDRlNGRlNWI0MBIaEhjKpMRclJU5Uwbe3qKoWhf+Y/2Xk0eAQDAS6SAK
      5iAS4yASxgEKC0NvbnNvcnRpdW1zErYBEmwKDWhoYUNvbnNvcnRpdW0SWxpAChVDaGFubmVsQ3Jl
      YXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMSiRwKB09yZGVyZXIS/RsS0BcKBmho
      YU1TUBLFFxrxFQoDTVNQEukVEt4VEtsVCgZoaGFNU1ASwgYtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQ1BEQ0NBZUtnQXdJQkFnSVVHRjlSSmNXdHA0N05IdHF0TzIrTG5Cb2JwdDB3Q2dZ
      SUtvWkl6ajBFQXdJdwpmREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Ua3dOd1lEVlFR
      REREQmpZUzVvYUdFdGJtVjBMbWhvWVdGdFltRnoKYzJGa2IzSXVZbXh2WTJ0amFHRnBiaTVzYVhW
      aVlXNXBibU11WTI0d0hoY05Nakl3TVRJM01EZ3hPVEkyV2hjTgpNalF4TVRFMk1EZ3hPVEkyV2pC
      OE1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3CkRRWURWUVFIREFa
      TWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4T1RBM0JnTlZCQU1NTUdOaExtaG8KWVMx
      dVpYUXVhR2hoWVcxaVlYTnpZV1J2Y2k1aWJHOWphMk5vWVdsdUxteHBkV0poYm1sdVl5NWpiakJa
      TUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk4rYUpKdTdPVnFEUmRRdHVzY2ZMbFN1
      cGh4Y2JhMXh4VDcrClFjWU9STnVxSDJLSC9IRGNRM25GeDlmOGpjcnV1M2FBVUN6QTdOb1N1T2VG
      Z1R0MUw0R2pRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dt
      TUIwR0ExVWREZ1FXQkJSMjlsSEJrSTFjTWVtTQpmNnFrSlZ1ZXB3MDYzekFLQmdncWhrak9QUVFE
      QWdOSUFEQkZBaUVBd3plMCtrc3NqbDZWVFNtMzhHd29NSEhrCjdoWkRKSVFaZkZiVXBGZUp0cWtD
      SUdGYWQvaktCNDVhZXYvbmE4UEIvSFNBWXoyV1FpNEUvNjkyM3gyU1g5Z3MKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhEQ0NBcGFn
      QXdJQkFnSVVXOUFrVy9XbC9OQTJHZmphUzh5Z2JzYzNobjR3Q2dZSUtvWkl6ajBFQXdJdwpmREVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Ua3dOd1lEVlFRREREQmpZUzVvYUdFdGJtVjBM
      bWhvWVdGdFltRnoKYzJGa2IzSXVZbXh2WTJ0amFHRnBiaTVzYVhWaVlXNXBibU11WTI0d0hoY05N
      akl3TVRJM01EZ3lNekF3V2hjTgpNak13TVRJM01EZ3lPREF3V2pCa01Rc3dDUVlEVlFRR0V3SkhR
      akViTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1Ck1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBj
      bVJsY21WeU1RNHdEQVlEVlFRTEV3VmhaRzFwYmpFV01CUUcKQTFVRUF3d05RV1J0YVc1QWFHaGhM
      VzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkZDNwo2MGpkbU1ZUGlBRHJV
      UU5tRjEzS1FqbXhtNEt5YUdsdm1yb0szN2RzKytjN09DWDVjdnVUM2x2N0lnek5FK291Cm00aHVP
      R0ljMkdlMkF5UzRDOUNqZ2dFTU1JSUJDREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFR
      SC8KQkFJd0FEQWRCZ05WSFE0RUZnUVVObE5WM3BaYjNXZWIxcStYQ1NyWWs5dW9mQWd3SHdZRFZS
      MGpCQmd3Rm9BVQpkdlpSd1pDTlhESHBqSCtxcENWYm5xY05PdDh3SkFZRFZSMFJCQjB3RzRJWlky
      RXRkRzl2YkhNdE5qYzJOV00xClpEazBPUzFyZUhNeWF6Q0JnUVlJS2dNRUJRWUhDQUVFZFhzaVlY
      UjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2kKZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0lt
      aG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eQpiMnhzYldWdWRFbEVJam9pUVdSdGFX
      NUFhR2hoTFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLCkJnZ3Foa2pPUFFRREFn
      TklBREJGQWlFQXhGeUQ2VjMxZEZXKzNFVzZKa084R1VsdGJ5eU5WVTZmRnhGd010NVEKaE5zQ0lE
      WWwvVkxaSDFUTDU2TXkzK3FiWnk5bEQ2TWN6NmlpT3RVbWk1QlphV012Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrCBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDUERDQ0FlS2dBd0lCQWdJVUdGOVJKY1d0cDQ3Tkh0cXRPMitMbkJvYnB0MHdDZ1lJS29a
      SXpqMEVBd0l3CmZERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVRrd053WURWUVFERERC
      allTNW9hR0V0Ym1WMExtaG9ZV0Z0WW1GegpjMkZrYjNJdVlteHZZMnRqYUdGcGJpNXNhWFZpWVc1
      cGJtTXVZMjR3SGhjTk1qSXdNVEkzTURneE9USTJXaGNOCk1qUXhNVEUyTURneE9USTJXakI4TVFz
      d0NRWURWUVFHRXdKSFFqRVBNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHcKRFFZRFZRUUhEQVpNYjI1
      a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeVpYSXhPVEEzQmdOVkJBTU1NR05oTG1obwpZUzF1WlhR
      dWFHaGhZVzFpWVhOellXUnZjaTVpYkc5amEyTm9ZV2x1TG14cGRXSmhibWx1WXk1amJqQlpNQk1H
      CkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTithSkp1N09WcURSZFF0dXNjZkxsU3VwaHhj
      YmExeHhUNysKUWNZT1JOdXFIMktIL0hEY1EzbkZ4OWY4amNydXUzYUFVQ3pBN05vU3VPZUZnVHQx
      TDRHalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBH
      QTFVZERnUVdCQlIyOWxIQmtJMWNNZW1NCmY2cWtKVnVlcHcwNjN6QUtCZ2dxaGtqT1BRUURBZ05J
      QURCRkFpRUF3emUwK2tzc2psNlZUU20zOEd3b01ISGsKN2haREpJUVpmRmJVcEZlSnRxa0NJR0Zh
      ZC9qS0I0NWFldi9uYThQQi9IU0FZejJXUWk0RS82OTIzeDJTWDlncwotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChoGQWRtaW5zIi8KB1dyaXRlcnMSJBIaCAESFhIIEgYIARICCAAaChIICgZoaGFN
      U1AaBkFkbWlucyIwCgZBZG1pbnMSJhIcCAESGBIIEgYIARICCAAaDBIKCgZoaGFNU1AQARoGQWRt
      aW5zIjMKC0VuZG9yc2VtZW50EiQSGggBEhYSCBIGCAESAggAGgoSCAoGaGhhTVNQGgZBZG1pbnMi
      LwoHUmVhZGVycxIkEhoIARIWEggSBggBEgIIABoKEggKBmhoYU1TUBoGQWRtaW5zKgZBZG1pbnMa
      2AEKDEthZmthQnJva2VycxLHARK8AQota2Fma2EtMC5icm9rZXIuaGhhLW5ldC5zdmMuY2x1c3Rl
      ci5sb2NhbDo5MDkyCi1rYWZrYS0xLmJyb2tlci5oaGEtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkw
      OTIKLWthZmthLTIuYnJva2VyLmhoYS1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mgota2Fma2Et
      My5icm9rZXIuaGhhLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyGgZBZG1pbnMaIgoNQ29uc2Vu
      c3VzVHlwZRIREgcKBWthZmthGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZB
      ZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rp
      b25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKB1Jl
      YWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVy
      cxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFs
      aWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucxqaAQoQT3JkZXJlckFkZHJlc3NlcxKFARJqCjNvcmRlcmVyMC5oaGFhbWJh
      c3NhZG9yLmJsb2NrY2hhaW4ubGl1YmFuaW5jLmNuOjg0NDMKM29yZGVyZXIxLmhoYWFtYmFzc2Fk
      b3IuYmxvY2tjaGFpbi5saXViYW5pbmMuY246ODQ0MxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMa
      JAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkK
      B1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZB
      ZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==
