apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: org1-cacerts-job
  namespace: org1-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: org1-cacerts-job
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: org1
      component_name: org1-net
      namespace: org1-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: http://101.36.106.59:8200
      authpath: devorg1-net-auth
      secretcryptoprefix: secretsv2/data/crypto/ordererOrganizations/org1-net/ca
      secretcredentialsprefix: secretsv2/data/credentials/org1-net/ca/org1
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.org1-net.org1ambassador.blockchain.liubaninc.cn
