apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sa-orderer1
  namespace: sa-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sa-orderer1
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: sa-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: saMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: sasc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://101.36.106.59:8200
      role: vault-role
      authpath: devsa-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/sa-net/orderers/orderer1.sa-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.sa-net.svc.cluster.local:9092
      - kafka-1.broker.sa-net.svc.cluster.local:9092
      - kafka-2.broker.sa-net.svc.cluster.local:9092
      - kafka-3.broker.sa-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: saambassador.blockchain.liubaninc.cn

    genesis: |-
      
