apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ccc-orderer1
  namespace: ccc-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ccc-orderer1
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local10
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: ccc-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: cccMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: cccsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://101.36.106.59:8200
      role: vault-role
      authpath: devccc-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/ccc-net/orderers/orderer1.ccc-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.ccc-net.svc.cluster.local:9092
      - kafka-1.broker.ccc-net.svc.cluster.local:9092
      - kafka-2.broker.ccc-net.svc.cluster.local:9092
      - kafka-3.broker.ccc-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: cccambassador.blockchain.liubaninc.cn

    genesis: |-
      CiIaINdijoP92/mebw5hkY43GEIwtLrEDF27C8yAb83X3uvzEuEiCt4iCtsiCngKWggBEAEaBgjU
      x76PBiIKc3lzY2hhbm5lbCpANDlhOTJiMDJiNjhmYjM5YmZkMjU1ZDBiMGQxYzI5ZDE3N2M4MGVk
      YWY2YmY0YWNhZjkxNDA0ZmIwYzk5ZTI0YxIaEhin04OhOelC64QpBoXczv94tDy8dbhFnhYS3iEK
      2yES2CESkxwKB09yZGVyZXIShxwS2hcKBmNjY01TUBLPFxr7FQoDTVNQEvMVEugVEuUVCgZjY2NN
      U1ASxwYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ1BUQ0NBZUtnQXdJQkFnSVVmQXBL
      cU9TNC9uTkVIWnZoTXZPb1VXclExYlV3Q2dZSUtvWkl6ajBFQXdJdwpmREVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1Ua3dOd1lEVlFRREREQmpZUzVqWTJNdGJtVjBMbU5qWTJGdFltRnoK
      YzJGa2IzSXVZbXh2WTJ0amFHRnBiaTVzYVhWaVlXNXBibU11WTI0d0hoY05Nakl3TVRJMU1EY3dO
      ek0zV2hjTgpNalF4TVRFME1EY3dOek0zV2pCOE1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVD
      QXdHVEc5dVpHOXVNUTh3CkRRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnla
      WEl4T1RBM0JnTlZCQU1NTUdOaExtTmoKWXkxdVpYUXVZMk5qWVcxaVlYTnpZV1J2Y2k1aWJHOWph
      Mk5vWVdsdUxteHBkV0poYm1sdVl5NWpiakJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhB
      MElBQk5RbWlTRlZ3TThkWVYwSE5lWEttbmdFZ1htcFZtSVZzTE83CnNpK1F2V3BtNjU1WGpEb3dr
      SlhVVVdjQkZKdStzK0tyUEMxVXZiR3hlTjNKOEszRmZvbWpRakJBTUE4R0ExVWQKRXdFQi93UUZN
      QU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTWjB4MzNvMjZ2anpqRwpQ
      cmZWcDYra3NDbmdZakFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBamg3dDNpV21YU3FJSGdUbkx4
      WVBLWGlOClFrT2wrbkVzUnVENmtyb3dCZ01DSVFDV01QUDZJaW9JNis1M0tzZ0NiV0Q2akd4ZSs1
      WUQ2Smt4MW5vbllReXoKb3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDN3pDQ0FwV2dBd0lCQWdJVU5GczdPclZROS9FSkwyNUps
      Ni9XNFJKcTRaVXdDZ1lJS29aSXpqMEVBd0l3CmZERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVRrd053WURWUVFERERCallTNWpZMk10Ym1WMExtTmpZMkZ0WW1GegpjMkZrYjNJdVlteHZZ
      MnRqYUdGcGJpNXNhWFZpWVc1cGJtTXVZMjR3SGhjTk1qSXdNVEkxTURjeE1UQXdXaGNOCk1qTXdN
      VEkxTURjeE5qQXdXakJrTVFzd0NRWURWUVFHRXdKSFFqRWJNQmtHQTFVRUJ4TVNOVEV1TlRBdkxU
      QXUKTVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0d0RBWURWUVFMRXdWaFpH
      MXBiakVXTUJRRwpBMVVFQXd3TlFXUnRhVzVBWTJOakxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0ND
      cUdTTTQ5QXdFSEEwSUFCRFdxCm53a3MwSExHTGNwREs1cXM0SzY1dTNzWkoxdHJNODM0VCsxVExq
      S0pDSXprSU1rMGJNOFBtSHlTMCsvSXhBVDkKZzRJYStlam9vaWdEdWd0V1pPaWpnZ0VMTUlJQkJ6
      QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFILwpCQUl3QURBZEJnTlZIUTRFRmdRVW1a
      UGdhS0ZEM0djSWxycEVsd3FJMk1nM0wxc3dId1lEVlIwakJCZ3dGb0FVCm1kTWQ5Nk51cjQ4NHhq
      NjMxYWV2cExBcDRHSXdJd1lEVlIwUkJCd3dHb0lZWTJFdGRHOXZiSE10T1RsbU56YzEKWmpkaUxY
      Y3lPVFJrTUlHQkJnZ3FBd1FGQmdjSUFRUjFleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lK
      MApjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENK
      b1ppNUZibkp2CmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCalkyTXRibVYwSWl3aWFHWXVWSGx3WlNJ
      NkltRmtiV2x1SW4xOU1Bb0cKQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUURUVUNGWHEyNk5tRUpheFRU
      TXpxSE5lR0VURnlvKzJFK2R4ZGJYREorUwp4d0lnQ09DVTlEZTJEUm55aWZpWFk2bzFDM2ZlUkJm
      amQ4UjgxYURpRHliNitZdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hB
      MjU2SscGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNQVENDQWVLZ0F3SUJBZ0lVZkFw
      S3FPUzQvbk5FSFp2aE12T29VV3JRMWJVd0NnWUlLb1pJemowRUF3SXcKZkRFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZ
      RFZRUUtEQWRQY21SbGNtVnlNVGt3TndZRFZRUUREREJqWVM1alkyTXRibVYwTG1OalkyRnRZbUZ6
      CmMyRmtiM0l1WW14dlkydGphR0ZwYmk1c2FYVmlZVzVwYm1NdVkyNHdIaGNOTWpJd01USTFNRGN3
      TnpNM1doY04KTWpReE1URTBNRGN3TnpNM1dqQjhNUXN3Q1FZRFZRUUdFd0pIUWpFUE1BMEdBMVVF
      Q0F3R1RHOXVaRzl1TVE4dwpEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5
      WlhJeE9UQTNCZ05WQkFNTU1HTmhMbU5qCll5MXVaWFF1WTJOallXMWlZWE56WVdSdmNpNWliRzlq
      YTJOb1lXbHVMbXhwZFdKaGJtbHVZeTVqYmpCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJOUW1pU0ZWd004ZFlWMEhOZVhLbW5nRWdYbXBWbUlWc0xPNwpzaStRdldwbTY1NVhqRG93
      a0pYVVVXY0JGSnUrcytLclBDMVV2Ykd4ZU4zSjhLM0Zmb21qUWpCQU1BOEdBMVVkCkV3RUIvd1FG
      TUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1oweDMzbzI2dmp6akcK
      UHJmVnA2K2tzQ25nWWpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQWpoN3QzaVdtWFNxSUhnVG5M
      eFlQS1hpTgpRa09sK25Fc1J1RDZrcm93QmdNQ0lRQ1dNUFA2SWlvSTYrNTNLc2dDYldENmpHeGUr
      NVlENkpreDFub25ZUXl6Cm93PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIw
      CgZBZG1pbnMSJhIcCAESGBIIEgYIARICCAAaDBIKCgZjY2NNU1AQARoGQWRtaW5zIjMKC0VuZG9y
      c2VtZW50EiQSGggBEhYSCBIGCAESAggAGgoSCAoGY2NjTVNQGgZBZG1pbnMiLwoHUmVhZGVycxIk
      EhoIARIWEggSBggBEgIIABoKEggKBmNjY01TUBoGQWRtaW5zIi8KB1dyaXRlcnMSJBIaCAESFhII
      EgYIARICCAAaChIICgZjY2NNU1AaBkFkbWlucyoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQK
      AjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0
      aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrYAQoMS2Fma2FCcm9rZXJzEscBErwBCi1rYWZrYS0w
      LmJyb2tlci5jY2MtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIKLWthZmthLTEuYnJva2VyLmNj
      Yy1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mgota2Fma2EtMi5icm9rZXIuY2NjLW5ldC5zdmMu
      Y2x1c3Rlci5sb2NhbDo5MDkyCi1rYWZrYS0zLmJyb2tlci5jY2MtbmV0LnN2Yy5jbHVzdGVyLmxv
      Y2FsOjkwOTIaBkFkbWlucxoiCg1Db25zZW5zdXNUeXBlEhESBwoFa2Fma2EaBkFkbWlucxoiCglC
      YXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRl
      cnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMS
      GBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zKgZBZG1pbnMSxgEKC0NvbnNvcnRpdW1zErYBEmwKDWNjY0NvbnNvcnRpdW0S
      WxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIA
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaLQoZQmxv
      Y2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxqFAgoQT3JkZXJlckFkZHJl
      c3NlcxLwARLUAQozb3JkZXJlcjAuY2NjYW1iYXNzYWRvci5ibG9ja2NoYWluLmxpdWJhbmluYy5j
      bjo4NDQzCjNvcmRlcmVyMS5jY2NhbWJhc3NhZG9yLmJsb2NrY2hhaW4ubGl1YmFuaW5jLmNuOjg0
      NDMKM29yZGVyZXIyLmNjY2FtYmFzc2Fkb3IuYmxvY2tjaGFpbi5saXViYW5pbmMuY246ODQ0Mwoz
      b3JkZXJlcjMuY2NjYW1iYXNzYWRvci5ibG9ja2NoYWluLmxpdWJhbmluYy5jbjo4NDQzGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5z
      GiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgD
      EgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAK
      AA==
