apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ccc-orderer3
  namespace: ccc-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ccc-orderer3
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local10
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: ccc-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer3
      loglevel: info
      localmspid: cccMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: cccsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://101.36.106.59:8200
      role: vault-role
      authpath: devccc-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/ccc-net/orderers/orderer3.ccc-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.ccc-net.svc.cluster.local:9092
      - kafka-1.broker.ccc-net.svc.cluster.local:9092
      - kafka-2.broker.ccc-net.svc.cluster.local:9092
      - kafka-3.broker.ccc-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: cccambassador.blockchain.liubaninc.cn

    genesis: |-
      CiIaIBSqL6mX2nfaUFw8pyS8Chy3CsKVm0pJWnKGVn73S6oVEr8iCrwiCrkiCngKWggBEAEaBgi7
      n8CPBiIKc3lzY2hhbm5lbCpAOGQ0M2Q2ZjQzYjJlNmU1OTZlZjYyMDZlZjI0MDIwYjFmMzhiZWUw
      MDNiODRhZDAyNDA0NjcwZmVlMzc1MzhkNxIaEhj7nNmYX/9dfxkoAJQ2ABS2CqMtrlHnW6MSvCEK
      uSEStiESxgEKC0NvbnNvcnRpdW1zErYBEmwKDWNjY0NvbnNvcnRpdW0SWxpAChVDaGFubmVsQ3Jl
      YXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMS8RsKB09yZGVyZXIS5RsSuBcKBmNj
      Y01TUBKtFxrZFQoDTVNQEtEVEsYVEsMVCgZjY2NNU1ASugYtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQ05EQ0NBZHFnQXdJQkFnSVVQZXNseVhMd0NLSXYvNFlvamdzZmx6UUxKblF3Q2dZ
      SUtvWkl6ajBFQXdJdwplREVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1Rd3dDZ1lEVlFRS0RBTmpZMk14T1RBM0JnTlZCQU1NTUdO
      aExtTmpZeTF1WlhRdVkyTmpZVzFpWVhOellXUnYKY2k1aWJHOWphMk5vWVdsdUxteHBkV0poYm1s
      dVl5NWpiakFlRncweU1qQXhNalV4TkRRM05UbGFGdzB5TkRFeApNVFF4TkRRM05UbGFNSGd4Q3pB
      SkJnTlZCQVlUQWtkQ01ROHdEUVlEVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WCkJBY01Ca3h2Ym1S
      dmJqRU1NQW9HQTFVRUNnd0RZMk5qTVRrd053WURWUVFERERCallTNWpZMk10Ym1WMExtTmoKWTJG
      dFltRnpjMkZrYjNJdVlteHZZMnRqYUdGcGJpNXNhWFZpWVc1cGJtTXVZMjR3V1RBVEJnY3Foa2pP
      UFFJQgpCZ2dxaGtqT1BRTUJCd05DQUFUZjBWOWJFU0lMYTRrQ2ZUYnNQUzZlUzRBZElLMFAxaEZr
      WCtCY3FJMFU5OS8yCnM4NTk0djFEdi8xTjZBdVIvdHBGcm5KRkJMMnJBUTdXY2ptMGZiQWVvMEl3
      UURBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCcGpBZEJnTlZIUTRF
      RmdRVVArZms4Yk9iTEdyTnFrRjdTUmJjaHZ0bApTNEl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlo
      QU00aDdLdW9rWDU5cHViTk01cCt5bE9oQlJnOVNmRm5tR1piCkR1b3pEdmd4QWlBYllYTnQwTm5Z
      OTFadWlnV2JaVHRNNGhQclJEZUZJVmpXSnBYdndLdW5JQT09Ci0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KIq4ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQXBHZ0F3SUJBZ0lV
      Ync4ZG0vR0xVT1Rxd1E3a014NWUyVDZSb2xRd0NnWUlLb1pJemowRUF3SXcKZURFTE1Ba0dBMVVF
      QmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUXd3
      Q2dZRFZRUUtEQU5qWTJNeE9UQTNCZ05WQkFNTU1HTmhMbU5qWXkxdVpYUXVZMk5qWVcxaVlYTnpZ
      V1J2CmNpNWliRzlqYTJOb1lXbHVMbXhwZFdKaGJtbHVZeTVqYmpBZUZ3MHlNakF4TWpVeE5EVXhN
      REJhRncweU16QXgKTWpVeE5EVTJNREJhTUdReEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRFZRUUhF
      eEkxTVM0MU1DOHRNQzR4TXk5TQpiMjVrYjI0eEVEQU9CZ05WQkFvVEIwOXlaR1Z5WlhJeERqQU1C
      Z05WQkFzVEJXRmtiV2x1TVJZd0ZBWURWUVFECkRBMUJaRzFwYmtCalkyTXRibVYwTUZrd0V3WUhL
      b1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFaXZENlUyNlQKb2hyT0tSRnExWlR1SnVGMHc1R1M5
      MkR5YWxSQWl6R0cvT0l3N2lEamhtWEZWUWhPRGN0QVc2MzJGSFpjRmp6WgpvTFhKWXFac2REUG5D
      YU9DQVFzd2dnRUhNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBCk1CMEdB
      MVVkRGdRV0JCUnJ0SktuVjYyZ2psNmFNcW8wMy96V3B5SzFDekFmQmdOVkhTTUVHREFXZ0JRLzUr
      VHgKczVzc2FzMnFRWHRKRnR5RysyVkxnakFqQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kwNU9X
      WTNOelZtTjJJdApNbkYwY200d2dZRUdDQ29EQkFVR0J3Z0JCSFY3SW1GMGRISnpJanA3SW1GaVlX
      TXVhVzVwZENJNkluUnlkV1VpCkxDSmhaRzFwYmlJNkluUnlkV1VpTENKb1ppNUJabVpwYkdsaGRH
      bHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWwKYm5SSlJDSTZJa0ZrYldsdVFHTmpZeTF1WlhRaUxD
      Sm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSQp6ajBFQXdJRFJ3QXdSQUlnZUkwV3Fv
      NWJwaXdyZWFQT2RqL0dXOVBVS3BOb3JNalNRdFl0T21FVVRhNENJQTRRCk9rNklwa0hQbi9IN09S
      OVg2QXNCdTlRblEzL0RtZEwrbVY4R0kyRCsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoE
      U0hBMhIGU0hBMjU2SroGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNORENDQWRxZ0F3
      SUJBZ0lVUGVzbHlYTHdDS0l2LzRZb2pnc2ZselFMSm5Rd0NnWUlLb1pJemowRUF3SXcKZURFTE1B
      a0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5
      dQpNUXd3Q2dZRFZRUUtEQU5qWTJNeE9UQTNCZ05WQkFNTU1HTmhMbU5qWXkxdVpYUXVZMk5qWVcx
      aVlYTnpZV1J2CmNpNWliRzlqYTJOb1lXbHVMbXhwZFdKaGJtbHVZeTVqYmpBZUZ3MHlNakF4TWpV
      eE5EUTNOVGxhRncweU5ERXgKTVRReE5EUTNOVGxhTUhneEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZ
      RFZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVgpCQWNNQmt4dmJtUnZiakVNTUFvR0ExVUVDZ3dEWTJO
      ak1Ua3dOd1lEVlFRREREQmpZUzVqWTJNdGJtVjBMbU5qClkyRnRZbUZ6YzJGa2IzSXVZbXh2WTJ0
      amFHRnBiaTVzYVhWaVlXNXBibU11WTI0d1dUQVRCZ2NxaGtqT1BRSUIKQmdncWhrak9QUU1CQndO
      Q0FBVGYwVjliRVNJTGE0a0NmVGJzUFM2ZVM0QWRJSzBQMWhGa1grQmNxSTBVOTkvMgpzODU5NHYx
      RHYvMU42QXVSL3RwRnJuSkZCTDJyQVE3V2NqbTBmYkFlbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFE
      CkFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVQK2ZrOGJPYkxHck5xa0Y3
      U1JiY2h2dGwKUzRJd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFNNGg3S3Vva1g1OXB1Yk5NNXAr
      eWxPaEJSZzlTZkZubUdaYgpEdW96RHZneEFpQWJZWE50ME5uWTkxWnVpZ1diWlR0TTRoUHJSRGVG
      SVZqV0pwWHZ3S3VuSUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIi8KB1Jl
      YWRlcnMSJBIaCAESFhIIEgYIARICCAAaChIICgZjY2NNU1AaBkFkbWlucyIvCgdXcml0ZXJzEiQS
      GggBEhYSCBIGCAESAggAGgoSCAoGY2NjTVNQGgZBZG1pbnMiMAoGQWRtaW5zEiYSHAgBEhgSCBIG
      CAESAggAGgwSCgoGY2NjTVNQEAEaBkFkbWlucyIzCgtFbmRvcnNlbWVudBIkEhoIARIWEggSBggB
      EgIIABoKEggKBmNjY01TUBoGQWRtaW5zKgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxII
      GgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxrYAQoMS2Fma2FC
      cm9rZXJzEscBErwBCi1rYWZrYS0wLmJyb2tlci5jY2MtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkw
      OTIKLWthZmthLTEuYnJva2VyLmNjYy1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mgota2Fma2Et
      Mi5icm9rZXIuY2NjLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyCi1rYWZrYS0zLmJyb2tlci5j
      Y2MtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIaBkFkbWlucxoiCg1Db25zZW5zdXNUeXBlEhES
      BwoFa2Fma2EaBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxC
      YXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoG
      QWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRh
      dGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJz
      GgZBZG1pbnMqBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMa
      LQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxqFAgoQT3JkZXJl
      ckFkZHJlc3NlcxLwARLUAQozb3JkZXJlcjAuY2NjYW1iYXNzYWRvci5ibG9ja2NoYWluLmxpdWJh
      bmluYy5jbjo4NDQzCjNvcmRlcmVyMS5jY2NhbWJhc3NhZG9yLmJsb2NrY2hhaW4ubGl1YmFuaW5j
      LmNuOjg0NDMKM29yZGVyZXIyLmNjY2FtYmFzc2Fkb3IuYmxvY2tjaGFpbi5saXViYW5pbmMuY246
      ODQ0Mwozb3JkZXJlcjMuY2NjYW1iYXNzYWRvci5ibG9ja2NoYWluLmxpdWJhbmluYy5jbjo4NDQz
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoG
      QWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4I
      AxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5z
      KgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
