apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zzzz-m0quorum
  namespace: zz-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: zzzz-m0quorum
  helmVersion: v3
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local10
    path: platforms/quorum/charts/node_quorum_member
  values:
    replicaCount: 1
    metadata:
      namespace: zz-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.4.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: zz-m0
      status: default
      consensus: ibft
      subject: O=zz-m0,OU=zz-m0,L=42.36/-71.06/Boston,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
        cakeshop: 8080
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://101.36.106.59:8200
      secretprefix: secretsv2/data/zz-quo/crypto/zz-m0
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumzz
    tessera:
      dburl: "jdbc:mysql://zz-m0-tessera:3306/demodb"
      dbusername: demouser
      url: "https://zz-m0.lm.blockchain.liubaninc.cn:443"
      clienturl: "http://zz-m0-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://zz-v0.lm.blockchain.liubaninc.cn
        - url: https://zz-v1.lm.blockchain.liubaninc.cn
        - url: https://zz-v2.lm.blockchain.liubaninc.cn
        - url: https://zz-m0.lm.blockchain.liubaninc.cn
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjFkZWVhOWEiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDc3Mjk2MzFkNDBiMDZiOGQwMWVmMjVhY2Y5OTlkYjkzZjcxMjA5YmY5NDMwOTAzMjdlZWMwY2RhNTVjZmVhOTI4MmU3NzljMzdlZWY0YWQxYTk5NGJjN2ZiNmM3MDBhNTEzZmMyNjMxMmQ0ZTcyYjIxNjc4Yjk3MWIxYzc5NGVhYTIxZmFmMThkYjk5NmNkMWJhZmVlNmJhOGEwOGM0ZWRiY2VkOGFiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICIzMDkwMzI3ZWVjMGNkYTU1Y2ZlYTkyODJlNzc5YzM3ZWVmNGFkMWE5IjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNzcyOTYzMWQ0MGIwNmI4ZDAxZWYyNWFjZjk5OWRiOTNmNzEyMDliZiI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImJjN2ZiNmM3MDBhNTEzZmMyNjMxMmQ0ZTcyYjIxNjc4Yjk3MWIxYzciOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICJlYWEyMWZhZjE4ZGI5OTZjZDFiYWZlZTZiYThhMDhjNGVkYmNlZDhhIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://ae4b7c3a4e5651e27124f88035180e48af9972110e61a622c0cdcdb228ad0f0f20729d3c652352517d724d572589b5c9f7bf349ab6d77a116bd5b31f41e6ce20@zz-v0.lm.blockchain.liubaninc.cn:10?discport=0",
    "enode://5fec194b1d99997b284f3904f8def1ec9054b74ae062c8db62aa19811bba3ebef222682d5e2ecde30377f8b54d91ba2dd0afa4289e954b367ebf3c6c031fa533@zz-v1.lm.blockchain.liubaninc.cn:20?discport=0",
    "enode://778ae2a5ce24a0c8f873048d3a62c4aceda1c48944f4f3fa7b0e9c454be098ed46c96235e021d8cef0a387f196f8edfd5cc77eeb08c62583e78bdaf0ba67ff96@zz-v2.lm.blockchain.liubaninc.cn:30?discport=0",
    "enode://c28ffe51649a33c2f72e1296dd6fac54b45c4a17de35ecf5af05cc41576f78f7873bbf707368afcea8a526b1ffe90886b9f6a371372c2a02bb267c0205dd8891@zz-m0.lm.blockchain.liubaninc.cn:0?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: zz-m0.lm.blockchain.liubaninc.cn
      portTM: 443
      rpcport: 1
      quorumport: 0
      cakeshopport: 4
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
