apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aaa-orderer0
  namespace: aaa-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: aaa-orderer0
  chart:
    git: https://github.com/liubaninc/bevel.git
    ref: local11
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: aaa-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer0
      loglevel: info
      localmspid: aaaMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: aaasc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://101.36.106.59:8200
      role: vault-role
      authpath: devaaa-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/aaa-net/orderers/orderer0.aaa-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.aaa-net.svc.cluster.local:9092
      - kafka-1.broker.aaa-net.svc.cluster.local:9092
      - kafka-2.broker.aaa-net.svc.cluster.local:9092
      - kafka-3.broker.aaa-net.svc.cluster.local:9092

    proxy:
      provider: haproxy
      external_url_suffix: aaaambassador.blockchain.liubaninc.cn

    genesis: |-
      CiIaILvEhrlTvbZ+hQBjftsfzS9gSwiPehr6C4cWzmZVIUYlEvYhCvMhCvAhCngKWggBEAEaBgjA
      jcmPBiIKc3lzY2hhbm5lbCpANjA3MTZlZDZkNzI3MmM3MjZmMTYwZGU5YzNmMmFhMGUzOTRjYjgz
      ZWY1ZTBkYThkYTRiYmJhZWEwNjBkZmJlOBIaEhh5tgVO2HSeCFHUgWkTy0u+Tf5SMmMoy+MS8yAK
      8CAS7SASkxwKB09yZGVyZXIShxwS2hcKBmFhYU1TUBLPFxr7FQoDTVNQEvMVEugVEuUVCgZhYWFN
      U1ASxwYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ1BUQ0NBZUtnQXdJQkFnSVVlQ3VF
      Nmk4KzhCcWJKQ0JyaTFSNTdvU1o2M3d3Q2dZSUtvWkl6ajBFQXdJdwpmREVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1Ua3dOd1lEVlFRREREQmpZUzVoWVdFdGJtVjBMbUZoWVdGdFltRnoK
      YzJGa2IzSXVZbXh2WTJ0amFHRnBiaTVzYVhWaVlXNXBibU11WTI0d0hoY05Nakl3TVRJM01EY3dO
      ekU0V2hjTgpNalF4TVRFMk1EY3dOekU0V2pCOE1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVD
      QXdHVEc5dVpHOXVNUTh3CkRRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnla
      WEl4T1RBM0JnTlZCQU1NTUdOaExtRmgKWVMxdVpYUXVZV0ZoWVcxaVlYTnpZV1J2Y2k1aWJHOWph
      Mk5vWVdsdUxteHBkV0poYm1sdVl5NWpiakJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhB
      MElBQkFOa0RuMmZJeVE4QlBnVFVnQ0N4dk5DNXhEd3Bpc05ybTEvCmtXaTRYVFJVSkRkejRYOHQ5
      b3RIMWZIb0pORTRYTGdwdmhGbEd1VWQzRWZIMXArRmUyR2pRakJBTUE4R0ExVWQKRXdFQi93UUZN
      QU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSandKS2Y2dTZ3TTFYZwpk
      dytGLzBBWHE0UzRLREFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBd01leTM4TmVkWWtZNllSbEk1
      Ums5S011Ck9LYWN0cWpmMmFRSDV5Q2p1eDRDSVFDWmhnSk8wcjB1TFRpbVQwQmFXcnFQcFhUQ3lU
      c3JIQkh2ME5IUVFyVGoKQlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiK2CC0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDOERDQ0FwYWdBd0lCQWdJVVI3U2VZUlpMUnZ0VVFxYzZ1
      T25OM1lSZTE4VXdDZ1lJS29aSXpqMEVBd0l3CmZERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxj
      bVZ5TVRrd053WURWUVFERERCallTNWhZV0V0Ym1WMExtRmhZV0Z0WW1GegpjMkZrYjNJdVlteHZZ
      MnRqYUdGcGJpNXNhWFZpWVc1cGJtTXVZMjR3SGhjTk1qSXdNVEkzTURjeE1EQXdXaGNOCk1qTXdN
      VEkzTURjeE5UQXdXakJrTVFzd0NRWURWUVFHRXdKSFFqRWJNQmtHQTFVRUJ4TVNOVEV1TlRBdkxU
      QXUKTVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0d0RBWURWUVFMRXdWaFpH
      MXBiakVXTUJRRwpBMVVFQXd3TlFXUnRhVzVBWVdGaExXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0ND
      cUdTTTQ5QXdFSEEwSUFCREdVCndnazdKR0d5VzRtZCtxYmdQQzhnWlVhVXd1QzUxb0FubjNsSXo3
      R2lmTE05dSs0UjNpZ3RWNzB2b3FlTThxMmkKdlFWZVd6RDM0bkNOSG9Qdk9oU2pnZ0VNTUlJQkNE
      QU9CZ05WSFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFILwpCQUl3QURBZEJnTlZIUTRFRmdRVTRz
      cm5TMndwMHBhQTY4cHFaRDYrMHpkamphd3dId1lEVlIwakJCZ3dGb0FVClk4Q1NuK3J1c0ROVjRI
      Y1BoZjlBRjZ1RXVDZ3dKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXZiSE10TnpjMlpEUTEKT1RjM1l5
      MW9OV3c0YlRDQmdRWUlLZ01FQlFZSENBRUVkWHNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpv
      aQpkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aWFHWXVSVzV5CmIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QVlXRmhMVzVsZENJc0ltaG1MbFI1Y0dV
      aU9pSmhaRzFwYmlKOWZUQUsKQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBOEV1RDR0TlF2UDdVeU5Y
      KzU3MGpnYk4xaWxhcDlvVzB1elVZTnZJaQp5RllDSUJqVEFRUFFOTEtIc25zWlRSendub0RGSHAw
      dXp3N0Rndm10Wnl0dzZTUDAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hB
      MjU2SscGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNQVENDQWVLZ0F3SUJBZ0lVZUN1
      RTZpOCs4QnFiSkNCcmkxUjU3b1NaNjN3d0NnWUlLb1pJemowRUF3SXcKZkRFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZ
      RFZRUUtEQWRQY21SbGNtVnlNVGt3TndZRFZRUUREREJqWVM1aFlXRXRibVYwTG1GaFlXRnRZbUZ6
      CmMyRmtiM0l1WW14dlkydGphR0ZwYmk1c2FYVmlZVzVwYm1NdVkyNHdIaGNOTWpJd01USTNNRGN3
      TnpFNFdoY04KTWpReE1URTJNRGN3TnpFNFdqQjhNUXN3Q1FZRFZRUUdFd0pIUWpFUE1BMEdBMVVF
      Q0F3R1RHOXVaRzl1TVE4dwpEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5
      WlhJeE9UQTNCZ05WQkFNTU1HTmhMbUZoCllTMXVaWFF1WVdGaFlXMWlZWE56WVdSdmNpNWliRzlq
      YTJOb1lXbHVMbXhwZFdKaGJtbHVZeTVqYmpCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VI
      QTBJQUJBTmtEbjJmSXlROEJQZ1RVZ0NDeHZOQzV4RHdwaXNOcm0xLwprV2k0WFRSVUpEZHo0WDh0
      OW90SDFmSG9KTkU0WExncHZoRmxHdVVkM0VmSDFwK0ZlMkdqUWpCQU1BOEdBMVVkCkV3RUIvd1FG
      TUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUmp3SktmNnU2d00xWGcK
      ZHcrRi8wQVhxNFM0S0RBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXdNZXkzOE5lZFlrWTZZUmxJ
      NVJrOUtNdQpPS2FjdHFqZjJhUUg1eUNqdXg0Q0lRQ1poZ0pPMHIwdUxUaW1UMEJhV3JxUHBYVEN5
      VHNySEJIdjBOSFFRclRqCkJRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIw
      CgZBZG1pbnMSJhIcCAESGBIIEgYIARICCAAaDBIKCgZhYWFNU1AQARoGQWRtaW5zIjMKC0VuZG9y
      c2VtZW50EiQSGggBEhYSCBIGCAESAggAGgoSCAoGYWFhTVNQGgZBZG1pbnMiLwoHUmVhZGVycxIk
      EhoIARIWEggSBggBEgIIABoKEggKBmFhYU1TUBoGQWRtaW5zIi8KB1dyaXRlcnMSJBIaCAESFhII
      EgYIARICCAAaChIICgZhYWFNU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCA
      gIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5l
      bFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFk
      bWlucxrYAQoMS2Fma2FCcm9rZXJzEscBErwBCi1rYWZrYS0wLmJyb2tlci5hYWEtbmV0LnN2Yy5j
      bHVzdGVyLmxvY2FsOjkwOTIKLWthZmthLTEuYnJva2VyLmFhYS1uZXQuc3ZjLmNsdXN0ZXIubG9j
      YWw6OTA5Mgota2Fma2EtMi5icm9rZXIuYWFhLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyCi1r
      YWZrYS0zLmJyb2tlci5hYWEtbmV0LnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTIaBkFkbWlucxoiCg1D
      b25zZW5zdXNUeXBlEhESBwoFa2Fma2EaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRl
      cnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMS
      GBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zKgZBZG1pbnMSxgEKC0NvbnNvcnRpdW1zErYBEmwKDWFhYUNvbnNvcnRpdW0S
      WxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIA
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFz
      aGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1
      Y3R1cmUSEBIGCP////8PGgZBZG1pbnMamgEKEE9yZGVyZXJBZGRyZXNzZXMShQESagozb3JkZXJl
      cjAuYWFhYW1iYXNzYWRvci5ibG9ja2NoYWluLmxpdWJhbmluYy5jbjo4NDQzCjNvcmRlcmVyMS5h
      YWFhbWJhc3NhZG9yLmJsb2NrY2hhaW4ubGl1YmFuaW5jLmNuOjg0NDMaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZB
      ZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=
